### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by stealth1188** [bitnami/bitnami-docker-redis-cluster#10]
Hi there, my pods are having issues reaching out to the internet to download the dependencies for some of the redis' modules (eg, redisgear and redisgraphs). For other PODs running (eg, Prometheus, Nginx), I'm able to reach google and other websites just fine. I may have an issue with my configuration and I'll need some assistance. 

As for connecting to the redis server external-IP via redis-cli, no issue there. RedisInsight is able to connect to the cluster just fine. Just need some assistance with the following if you will, please:

1) Would you please let me know what Parameters I need to change on my yaml file (attached) in order for my pods to reach out to the Internet?
2) Instead of setting the parameter "cluster.externalAccess.service.loadBalancerIP[0]=10.87.242.221,\cluster.externalAccess.service.loadBalancerIP[1]=10.87.242.222,\...etc" during helm install, can you show me the proper array format under the values.yaml file for each of the loadBalanceIP.

loadBalancerIP: [] ???

Thank you in advance,
A
[Github-Q-Redis-Install-Info.txt](https://github.com/bitnami/bitnami-docker-redis-cluster/files/5084788/Github-Q-Redis-Install-Info.txt)

**Comment by stealth1188** [comment]
Values Production file attached: 

[values-production.txt](https://github.com/bitnami/bitnami-docker-redis-cluster/files/5084795/values-production.txt)

**Comment by stealth1188** [comment]
Nevermind. Enabled NetworkPolicy by mistake. Sorry for the trouble and was kinda in a rush to get redis up and running. Sigh...thanks y'all.

**Comment by juan131** [comment]
We are glad you were able to solver the issue by your own means. Please do not hesitate to let us know if there is anything else we can help you with.
