### ISSUE TITLE
RedisGear

### ISSUE THREAD

**Issue by stealth1188** [bitnami/bitnami-docker-redis-cluster#11]
Hi there,
I have downloaded the pre-compiled version of RedisGear directly from RedisLab (https://redislabs.com/download-center/modules/?_ga=2.207907090.1662453696.1597464632-1901181222.1593647792). However, I'm having an issue loading it after updating the configmap (loadmodule /bitnami/redis/data/modules/finalmodules/redisgears.so). Is there anyway I can install the dependencies manually without using http://redismodules.s3.amazonaws.com/redisgears/redisgears-dependencies.linux-centos7-x64.1.0.1.tgz for Debian?
And if anyone can share their experience or even willing to share his/her pre-compiled module for Debian (and provide info of the required dependencies), that would be even better!

All other modules loads and runs great! 

Free Pre-Compiled Modules (just need an account and it's free to signup - sharing the info in case anyone is interested):
https://redislabs.com/download-center/modules/?_ga=2.207907090.1662453696.1597464632-1901181222.1593647792.

Thank you in advance!

Snippet of the error:
1:M 20 Aug 2020 00:03:35.353 * Module 'ft' loaded from /bitnami/redis/data/modules/finalmodules/module-enterprise.so
1:M 20 Aug 2020 00:03:35.354 * Module 'bf' loaded from /bitnami/redis/data/modules/finalmodules/redisbloom.so
1:M 20 Aug 2020 00:03:35.356 * <rg> RedisGears version 1.0.1, git_sha=155ef626ae6f728e9d9c646cf810954d8c51b9ab, compiled_os=linux-centos7-x64
1:M 20 Aug 2020 00:03:35.356 * <rg> Redis version found by RedisGears : 6.0.6 - oss
1:M 20 Aug 2020 00:03:35.356 * <rg> MaxExecutions:1000
1:M 20 Aug 2020 00:03:35.356 * <rg> MaxExecutionsPerRegistration:100
1:M 20 Aug 2020 00:03:35.356 * <rg> ProfileExecutions:0
1:M 20 Aug 2020 00:03:35.356 * <rg> PythonAttemptTraceback:1
1:M 20 Aug 2020 00:03:35.356 * <rg> DependenciesUrl:http://redismodules.s3.amazonaws.com/redisgears/redisgears-dependencies.linux-centos7-x64.1.0.1.tgz
1:M 20 Aug 2020 00:03:35.356 * <rg> DependenciesSha256:896214f567a7b6a86107d80169c65be28d40e077934a2234b2bab2daac239292
1:M 20 Aug 2020 00:03:35.356 * <rg> CreateVenv:0
1:M 20 Aug 2020 00:03:35.356 * <rg> ExecutionThreads:3
1:M 20 Aug 2020 00:03:35.356 * <rg> ExecutionMaxIdleTime:5000
1:M 20 Aug 2020 00:03:35.356 * <rg> PythonInstallReqMaxIdleTime:30000
1:M 20 Aug 2020 00:03:35.357 * <rg> PythonInstallationDir:/var/opt/redislabs/modules/rg
1:M 20 Aug 2020 00:03:35.357 * <rg> DownloadDeps:1
1:M 20 Aug 2020 00:03:35.357 * <rg> ForceDownloadDepsOnEnterprise:0
1:M 20 Aug 2020 00:03:35.357 * <rg> SendMsgRetries:3
1:M 20 Aug 2020 00:03:35.357 # <rg> could not initialize RedisAI_GetLLAPIVersion
1:M 20 Aug 2020 00:03:35.357 # <rg> could not initialize RediAI api, running without AI support.
1:M 20 Aug 2020 00:03:35.357 * <rg> PYENV_DIR: /var/opt/redislabs/modules/rg//python3_1.0.1/
1:M 20 Aug 2020 00:03:35.357 * <rg> PYENV_HOME_DIR: /var/opt/redislabs/modules/rg//python3_1.0.1//.venv/
1:M 20 Aug 2020 00:03:35.357 * <rg> PYENV_BIN_DIR: /var/opt/redislabs/modules/rg//python3_1.0.1//.venv//bin
1:M 20 Aug 2020 00:03:35.357 * <rg> PYENV_ACTIVATE: /var/opt/redislabs/modules/rg//python3_1.0.1//.venv//bin/activate_this.py
1:M 20 Aug 2020 00:03:35.357 * <rg> PYENV_ACTIVATE_SCRIPT: /var/opt/redislabs/modules/rg//python3_1.0.1//.venv//bin/activate
1:M 20 Aug 2020 00:03:35.357 * <rg> Executing : rm -rf /tmp/deps..896214f567a7b6a86107d80169c65be28d40e077934a2234b2bab2daac239292.tgz
1:M 20 Aug 2020 00:03:35.359 * <rg> Executing : curl -o /tmp/deps..896214f567a7b6a86107d80169c65be28d40e077934a2234b2bab2daac239292.tgz http://redismodules.s3.amazonaws.com/redisgears/redisgears-dependencies.linux-centos7-x64.1.0.1.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   799  100   799    0     0  19023      0 --:--:-- --:--:-- --:--:-- 19023
1:M 20 Aug 2020 00:03:35.412 # <rg> Failed on sha 256 comparison
1:M 20 Aug 2020 00:03:35.412 # <rg> Failed installing python dependencies
1:M 20 Aug 2020 00:03:35.412 # Module /bitnami/redis/data/modules/finalmodules/redisgears.so initialization failed. Module not loaded
1:M 20 Aug 2020 00:03:35.412 # Can't load module from /bitnami/redis/data/modules/finalmodules/redisgears.so: server aborting

**Comment by rafariossaa** [comment]
Hi,
  I think this should be better asked in redis' forums, to have a better idea of what is needed to have that module installed.
  If it is going to download and install other files, most probably you will hit permissions issues because the user that runs redis doesn't have permissions on all the file system.

**Comment by stealth1188** [comment]
Gotcha.
Before reaching out to someone on the redis forum - I gave the below a try.
Manually compiled from https://github.com/RedisGears/RedisGears and it works like a champ!

**Comment by rafariossaa** [comment]
Hi, 
  Thanks from sharing your workaround.
