### ISSUE TITLE
Name "name":"redis-A-B" not work , it work with "name":"redis-A"

### ISSUE THREAD

**Issue by rampatnaik** [bitnami/bitnami-docker-redis-cluster#17]
Hello Redis

I am using  version=11.1.1 , the  Naming of redis doesnot work as per our project 
Name "name":"redis-A-B" not work , it work with "name":"redis-A"
I am using spinnaker , K8s: 17 version with  eks

error :
Error from server (Invalid): error when applying patch:
for: "STDIN": StatefulSet.apps "redis-A-B-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error from server (Invalid): error when applying patch:

**Comment by rampatnaik** [comment]
After I delete StatefulSet manually then it work

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure about this issue.
  The error you got means that when updating you only can change the indicated parameters. If you want to rename it you need to run it the first time with that name.

**Comment by rafariossaa** [comment]
Hi,
 Due to inactivity, I am closing this issue.
 Please, don't hesitate to reopen it if needed.
