### ISSUE TITLE
Install Redis Cluster in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-redis-cluster#21]
Redis Cluster is a fast, open source, in-memory key value data structure store that works as an active-passive cluster implementation that consists of master and slave nodes. This documentation will teach you how to install Redis Cluster in the IBM Cloud using the Kubernetes Cluster Service.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105731514-7e156400-5efd-11eb-8821-06899230ab79.png)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105731565-89688f80-5efd-11eb-9104-48af202ff76d.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements as the following ones are selected as default for the tutorial,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105731592-8ff70700-5efd-11eb-80ab-3b143756a380.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105731610-94232480-5efd-11eb-8ad2-b81d83eae45a.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105731632-98e7d880-5efd-11eb-9204-3719a7b4b15c.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105731666-a1d8aa00-5efd-11eb-97ca-3f1a2b52c9fe.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105731688-a7ce8b00-5efd-11eb-87c3-6f158a510661.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105731746-b6b53d80-5efd-11eb-8484-5842dc0bc429.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105731759-bb79f180-5efd-11eb-8061-7ccf759c33f3.PNG)

## Step 3: Install Redis

* Click on the search section at the top of the main page, type Redis, and click on Redis Cluster Packaged by Bitnami.

![Redis1](https://user-images.githubusercontent.com/70336951/105731904-eb28f980-5efd-11eb-9d10-ea60ec43cc31.PNG)

* A new window opens, select the cluster and enter the name you want for the Redis Cluster workspace or select an exist workspace, in this case, we'll create a new one and it will be called _rediscluster-example_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/redis-cluster#about "here").

![Redis2](https://user-images.githubusercontent.com/70336951/105731922-f0864400-5efd-11eb-9fe1-b14f06a701cb.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105731952-f5e38e80-5efd-11eb-97a1-9c803c0ba02e.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105731968-fb40d900-5efd-11eb-818d-c1dd48388550.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105731980-00058d00-5efe-11eb-97d7-cb326e7b3c86.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105731998-03007d80-5efe-11eb-90b2-900ea83bcc00.PNG)

* Once you have installed the terminal, open it, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *rediscluster-example* is now active.

`$ kubectl get ns`

![testredis1](https://user-images.githubusercontent.com/70336951/105732030-07c53180-5efe-11eb-9931-e1e2e3ebf60e.PNG)

* You can then obtain more data about the service and it's pods. As you can see Redis Cluster has master and slave nodes.

`$ kubectl get pod -n NAMESERVICE -o wide`

![testredis2](https://user-images.githubusercontent.com/70336951/105732044-0b58b880-5efe-11eb-802a-720829dec907.PNG)

`$ kubectl get service -n NAME SERVICE`

![testredis3](https://user-images.githubusercontent.com/70336951/105732062-0f84d600-5efe-11eb-8c50-521f72ea76b6.PNG)

* Select the master pod within your service using bash.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

* And finally, check if Redis Cluster is correctly installed by checking the server version in the master node.

` redis server -v `

![testredis4](https://user-images.githubusercontent.com/70336951/105732091-16abe400-5efe-11eb-8940-b46f21f47f91.PNG)

You have finished the installation, enjoy your Redis installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
