### ISSUE TITLE
redis-cluster:6.0-debian-10 initialization hangs

### ISSUE THREAD

**Issue by Imaskar** [bitnami/bitnami-docker-redis-cluster#26]
**Description**

I am using `docker.io/bitnami/redis-cluster:6.0-debian-10` in my integration tests with docker-compose. I first start the cluster, then tail to the coordinator process to know when the cluster is ready. On `2021-04-26` my integration tests started hanging indefinitely while waiting for the cluster to become ready. The reason is that `6.0-debian-10` has changed from `6.0.12-debian-10-r44` which was working to `6.0.13-debian-10-r0` which hangs.

Workaround: change `6.0-debian-10` to `6.0.13-debian-10-r0`

**Steps to reproduce the issue:**

1. Run redis-cluster:6.0.13-debian-10-r0 with 3-3 configuration
2. Attach to the cluster creator container with `docker-compose -f` to know when the cluster is ready

**Describe the results you received:**

The process never finishes. The last log line is: 
```redis-cluster-init_1  | 2021-05-04T13:24:33.664432700Z redis-server "${ARGS[@]}"```

**Describe the results you expected:**

The process finishes when the cluster is ready.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is stable to reproduce.

**Version**

- Broken version: `bitnami/redis-cluster:6.0.13-debian-10-r0`

- Working version`bitnami/redis-cluster:6.0.12-debian-10-r44`

**Comment by alvneiayu** [comment]
hi @Imaskar 

I can reproduce the problem but I am not sure if it is the same reason (the volumes are not empty). Could you share with me logs, please?

Please include in enviroment:

```
BITNAMI_LOG_LEVEL=trace8
```

Thanks a lot.

Álvaro

**Comment by Imaskar** [comment]
Sorry for the delay.
[redis-cluster.log](https://github.com/bitnami/bitnami-docker-redis-cluster/files/6446311/redis-cluster.log)

With the debug variable the order of messages changes and I see a new one:

`[ERR] Node 172.24.0.4:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.`

**Comment by Imaskar** [comment]
I don't see any content on the node, though.
```
$ cat bitnami/redis/data/dump.rdb
REDIS0009�      redis-ver6.0.13�
redis-bits�@�ctime�@]�`used-mem�Pi(�repl-stream-db��repl-id(c3ec8d169470cb69961501d036e503991009de9d�
                                                                                                     repl-offset��
                                                                                                                  aof-preamble��m       jG}�$ 
$ redis-cli
127.0.0.1:6379> keys *
(empty array)
```

**Comment by alvneiayu** [comment]
hi @Imaskar 

I am investigating the problem. I think that it is a problem with the persistence. I will come back as soon I have more information.

Sorry for the delay and thanks for your patience

Álvaro

**Comment by alvneiayu** [comment]
hi @Imaskar 
Could you try setting up the flag REDIS_CLUSTER_CREATOR to no, please? It seems that your volumes are already created and Redis is trying to create again the cluster.

Let me know if you can still reproduce your problem.

Thanks a lot

Álvaro

**Comment by Imaskar** [comment]
Hi @alvneiayu . If I set `REDIS_CLUSTER_CREATOR` to no or omit it, the nodes can't form the cluster, they start on their own. I also see the message 
```
[ERR] Node 172.28.0.5:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0.
```
even with the older, working image, but it still works: forms the cluster and exits without an error code. It is shown if I run docker compose up again after running it before. If I do `docker system prune`, the message disappears.

**Comment by alvneiayu** [comment]
Hi @Imaskar 

My colleague @miguelaeh has created a change as you can see above. The change is not already merged. Could you do a test modifying your run.sh and compiling the container to use it in your docker-compose?.

I think that the problem is solved but just to verify it.

Thanks a lot

Álvaro
