### ISSUE TITLE
"nodes.conf: No such file or directory"

### ISSUE THREAD

**Issue by PojahnM** [bitnami/bitnami-docker-redis-cluster#30]
I am using the [docker compose](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) file in this repository without any modifications and run `docker-compose up -d`. The first service(`redis-node-0`) always fails with the same error message:

`sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory`

Full logs:

```
redis-cluster 11:06:24.26
redis-cluster 11:06:24.26 Welcome to the Bitnami redis-cluster container
redis-cluster 11:06:24.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis-cluster
redis-cluster 11:06:24.26 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis-cluster/issues
redis-cluster 11:06:24.26
redis-cluster 11:06:24.26 INFO  ==> ** Starting Redis setup **
redis-cluster 11:06:24.29 INFO  ==> Initializing Redis
redis-cluster 11:06:24.30 INFO  ==> Setting Redis config file
Changing old IP 172.26.0.7 by the new one 172.22.0.3
sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory
```

All the other nodes start without any issues. It's only the first one that's a failing. I tried changing version to `latest`, `6.2.4` and `6.2-debian-10` without any luck. 

I googled and found people with similar problems. They were however trying to run it in Kubernetes and the solution wasn't applicable to docker/docker-compose.

I am using Mac OS 11.3 (Big Sur) and Docker Desktop For Mac 3.5.1.

**Comment by alvneiayu** [comment]
Hi @PojahnM

I tested in Mac Os 11.4 (Big Sur) with Docker desktop for Mac 3.5.1 and I can not reproduce your problem. Maybe it is a problem with permissions in your folder or maybe something with the volumes.

Could you try removing the volumes and launch again (docker-compose down -v && docker-compose up)?

Thanks a lot

Álvaro

**Comment by PojahnM** [comment]
Thanks for looking into this. Your suggestion worked!  🎉 

Sorry for being bad at Docker.

**Comment by PojahnM** [comment]
While we're at it, how to we connect to the cluster from a client based on the Docker host? 

I keep getting `Unable to connect to [172.25.0.5:7000]: connection timed out: /172.25.0.5:7000`. I set `spring.redis.cluster.nodes` to `localhost:7000` in my properties file and I exposed the right ports in docker-compose.

**Comment by alvneiayu** [comment]
hi @PojahnM 

[Here](https://github.com/bitnami/bitnami-docker-redis-cluster#configuration-file), you can find the possible env variables that you can use to configure the Bitnami Redis Cluster docker. I am not expert in Redis Cluster but I think that you can configure everything just using env variables in the Readme.

Thanks a lot

Álvaro
