### ISSUE TITLE
Missing arm64 image (for Apple M1 chip)

### ISSUE THREAD

**Issue by semisedlak** [bitnami/bitnami-docker-redis-cluster#31]
Hey 👋,
can you tell when (or if) will you prepare redis-cluster image for arm64 architecture?
Have a nice day.

**Comment by javsalgar** [comment]
Hi,

I am afraid we still cannot provide an exact date. It is in our plans but depending on priorities we don't know when we will work on it. As soon as there are more news we will update the ticket.

**Comment by utobi** [comment]
Hi @javsalgar, sorry to bother you but are there any updates on this by now? Thank you!

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. We've done some feasibility studies but I still cannot provide a date on when this will be available.

**Comment by vannb** [comment]
Dear sir, do we have any update on this?

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
