### ISSUE TITLE
It seems that the cluster must be initialized properly when all machines are online? 

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [bitnami/bitnami-docker-redis-cluster#37]
https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml

When using this example, assuming an initial 100 machines, it may take 100 machines online at the same time to initialize, so incremental updates like "bitnami/bitnami-docker-mariadb-galera" are not possible. I would like to ask now is there any way to make one machine can also run normally, when adding other machines can be incremental update?

I assume that there may be a situation where a part of the machine can be turned off during low traffic, and a few preset nodes can be turned on or even added to cope with this situation when there is a lot of traffic. I wonder if there are any existing solutions that can be implemented?

**Comment by marcosbc** [comment]
Hi @Conmi-WhiteJoker, it should be possible for you to create an initial deployment with at least 3 nodes, then scale it to a bigger value. You can see the [Bitnami chart for Redis Cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology) where this scenario is supported.

**Comment by Conmi-WhiteJoker** [comment]
> Hi @Conmi-WhiteJoker, it should be possible for you to create an initial deployment with at least 3 nodes, then scale it to a bigger value. You can see the [Bitnami Helm chart for Redis Cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology) where this scenario is supported on Kubernetes environments.

Thank you for your suggestion. I will test the feasibility of this example. Thank you very much.

**Comment by Conmi-WhiteJoker** [comment]
> Hi @Conmi-WhiteJoker, it should be possible for you to create an initial deployment with at least 3 nodes, then scale it to a bigger value. You can see the [Bitnami Helm chart for Redis Cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology) where this scenario is supported on Kubernetes environments.

I created a "redis-node-6" with the same configuration as "redis-node-5", but didn't add the node to each of the original node configurations, and it went undetected.  Perhaps the current framework does not allow for incremental master nodes.  Is my configuration incorrect?  

`
version: "2"
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDISCLI_AUTH=bitnami"
      - "REDIS_CLUSTER_REPLICAS=1"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
      - "REDIS_CLUSTER_CREATOR=yes"

  redis-node-6:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-6:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - "REDIS_PASSWORD=bitnami"
      - "REDISCLI_AUTH=bitnami"
      - "REDIS_CLUSTER_REPLICAS=1"
      - "REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6"
      - "REDIS_CLUSTER_CREATOR=yes"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

`

**Comment by Conmi-WhiteJoker** [comment]
> Hi @Conmi-WhiteJoker, it should be possible for you to create an initial deployment with at least 3 nodes, then scale it to a bigger value. You can see the [Bitnami Helm chart for Redis Cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology) where this scenario is supported on Kubernetes environments.

My idea is that Redis can add master nodes incrementally to increase capacity, throughput, and high availability. 

Bitnami's Mariadb allows single-node clusters to be incrementally expanded as long as they are configured with enough machines (I tested 100 nodes, node 1 can run on its own when started, node 2 can join directly after checking the cluster environment, node 3 can do the same, and so on). 

But I don't know if Redis is capable of that. 

Hope to get answers, thank you.

**Comment by marcosbc** [comment]
@Conmi-WhiteJoker With the current deployment options, it is not possible as you need to specify for each Redis nodes, which nodes are inside the cluster.

If you want something more advanced, with discoverability (i.e. so you don't need to hardcode the list of nodes), I would recommend checking out Redis with sentinel enabled.

**Comment by Conmi-WhiteJoker** [comment]
> @Conmi-WhiteJoker ‎使用当前的部署选项，由于您需要为每个 Redis 节点指定集群内有哪些节点，因此无法实现。‎
> 
> ‎如果你想要一些更高级的东西，具有可发现性（即你不需要硬编码节点列表），我建议你看看启用了哨兵的Redis。‎

No, no, no, my friend marcosbc, what I want is not a guarantee that redis can be made up of layers like a mechanical design. She wanted her to be like a strong girl, with muscles that no one else could see, muscles that only showed up when they were needed.

Let's say I started with three nodes and reserved 100 master hosts in the cluster, and when I encountered an enemy for the first time I only needed 10 nodes (application scenario), I just needed to select 7 nodes from the external server farm and put them into the cluster.

My idea is to create a master service for a cluster of 100 Redis and start some nodes as needed (assuming surge requests come in) and shut down some nodes as needed (after the day's peak has passed).
Right now the framework is configured with 100 clusters, but they all have to be online to start properly, which is a hassle. What I want is for the framework to do incremental backup, like Bitnami's MariaDB!

As long as "MARIADB_GALERA_CLUSTER_ADDRESS" is configured with 100 databases, after the first one is successful, the other ones with hostname in the configuration can be added to the cluster. You do not need all booting to enter the cluster.
I wonder if it can be implemented in Redis?

https://github.com/bitnami/bitnami-docker-mariadb-galera：
$ docker run -d --name mariadb-galera-0 \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  -e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes \
  -e MARIADB_USER=my_user \
  -e MARIADB_PASSWORD=my_password \
  -e MARIADB_DATABASE=my_database \
  -e MARIADB_REPLICATION_USER=my_replication_user \
  -e MARIADB_REPLICATION_PASSWORD=my_replication_password \
  bitnami/mariadb-galera:latest

$ docker run -d --name mariadb-galera-1 --link mariadb-galera-0:mariadb-galera \
  -e MARIADB_GALERA_CLUSTER_NAME=my_galera \
  -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567 \
  -e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user \
  -e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password \
  -e MARIADB_ROOT_PASSWORD=my_root_password \
  -e MARIADB_REPLICATION_USER=my_replication_user \
  -e MARIADB_REPLICATION_PASSWORD=my_replication_password \
  bitnami/mariadb-galera:latest

**Comment by Conmi-WhiteJoker** [comment]
> @Conmi-WhiteJoker With the current deployment options, it is not possible as you need to specify for each Redis nodes, which nodes are inside the cluster.
> 
> If you want something more advanced, with discoverability (i.e. so you don't need to hardcode the list of nodes), I would recommend checking out Redis with sentinel enabled.

No, no, no, my friend marcosbc, what I want is not a guarantee that redis can be made up of layers like a mechanical design. She wanted her to be like a strong girl, with muscles that no one else could see, muscles that only showed up when they were needed.

Let's say I started with three nodes and reserved 100 master hosts in the cluster, and when I encountered an enemy for the first time I only needed 10 nodes (application scenario), I just needed to select 7 nodes from the external server farm and put them into the cluster.

My idea is to create a master service for a cluster of 100 Redis and start some nodes as needed (assuming surge requests come in) and shut down some nodes as needed (after the day's peak has passed).
Right now the framework is configured with 100 clusters, but they all have to be online to start properly, which is a hassle. What I want is for the framework to do incremental backup, like Bitnami's MariaDB!

As long as "MARIADB_GALERA_CLUSTER_ADDRESS" is configured with 100 databases, after the first one is successful, the other ones with hostname in the configuration can be added to the cluster. You do not need all booting to enter the cluster.
I wonder if it can be implemented in Redis?

https://github.com/bitnami/bitnami-docker-mariadb-galera：
$ docker run -d --name mariadb-galera-0
-e MARIADB_GALERA_CLUSTER_NAME=my_galera
-e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
-e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
-e MARIADB_ROOT_PASSWORD=my_root_password
-e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
-e MARIADB_USER=my_user
-e MARIADB_PASSWORD=my_password
-e MARIADB_DATABASE=my_database
-e MARIADB_REPLICATION_USER=my_replication_user
-e MARIADB_REPLICATION_PASSWORD=my_replication_password
bitnami/mariadb-galera:latest

$ docker run -d --name mariadb-galera-1 --link mariadb-galera-0:mariadb-galera
-e MARIADB_GALERA_CLUSTER_NAME=my_galera
-e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera:4567,0.0.0.0:4567
-e MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
-e MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
-e MARIADB_ROOT_PASSWORD=my_root_password
-e MARIADB_REPLICATION_USER=my_replication_user
-e MARIADB_REPLICATION_PASSWORD=my_replication_password
bitnami/mariadb-galera:latest

**Comment by marcosbc** [comment]
@Conmi-WhiteJoker The problem with Redis Cluster, there is no "multi-master" support, so the topology is static. Note that what is most similar to MariaDB Galera is not the Redis Cluster solution, but the Redis with Sentinel solution (despite the confusing name of both): https://github.com/bitnami/bitnami-docker-redis-sentinel

**Comment by Conmi-WhiteJoker** [comment]
> @Conmi-WhiteJoker The problem with Redis Cluster, there is no "multi-master" support, so the topology is static. There isn't any discoverability either, which is what Galera provides to MariaDB.
> 
> Note that what is most similar to MariaDB Galera is **not** the Redis Cluster solution, but the Redis with Sentinel solution: https://github.com/bitnami/bitnami-docker-redis-sentinel

Oh, I see. Sorry to trouble you for so long and thank you for your help.
