### ISSUE TITLE
Cluster Recovery from Failure

### ISSUE THREAD

**Issue by brettnem** [bitnami/bitnami-docker-redis-cluster#38]
Hello All,
What's the right way to recover from a cluster failure? I know this might be more of a Redis question than a cluster config question, but I think it's relevant since people using this recipe may run into this issue. 

I'm not sure why, but i had nodes that were OOM Killed. When I brought them back up, they had different IPs. The cluster thinks it knows it's topology, but those servers are all on different IPs now. The slots and data should all be good still.. So how do I get the cluster to sync back up? 

I have done a service update --force to bump them all.. but they can't find each other. 

Thanks

**Comment by carrodher** [comment]
As you rightly said, for information regarding the application itself or customization of the content within the application; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
