### ISSUE TITLE
Inconsistency format of REDIS_NODES environment variables

### ISSUE THREAD

**Issue by tommy9690** [bitnami/bitnami-docker-redis-cluster#46]
### Name and Version

docker.io/bitnami/redis-cluster:6.2

### What steps will reproduce the bug?

docker container failed to run when put port number in `REDIS_NODES` env variables

### What is the expected behavior?

docker container run successfully when put port number in `REDIS_NODES` env variables

### What do you see instead?

https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/7.0/debian-11/rootfs/opt/bitnami/scripts/librediscluster.sh

In above file, `redis_cluster_create` process the nodes using `to_host_and_port` function while the `redis_cluster_update_ips` didn't do that

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the input! As you spotted the function that does not consider ports, would you like to submit a PR fixing it?
