### ISSUE TITLE
arm processor support for multi arch for bitnami/redis image 

### ISSUE THREAD

**Issue by kdbmadhavi** [bitnami/bitnami-docker-redis-cluster#47]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

While trying to deploy in kubernetes with arm processor type nodes ,we are facing issue

### What do you see instead?

CrashLoopbackOff issue arising

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
