### ISSUE TITLE
How can I inject my custom module?

### ISSUE THREAD

**Issue by marghidanu** [bitnami/bitnami-docker-redis-cluster#8]
I've been trying to inject a custom module by creating a new Docker image using the bitnami-docker-redis-cluster as a base, but there's no way to inject it in the configuration. 

Would be nice to be able to pass some additional parameters at startup.

**Comment by javsalgar** [comment]
Hi,

Thank you for using bitnami. Are you using our helm chart or the docker-compose?

**Comment by marghidanu** [comment]
Hello, 

I am using the Helm chart. I eventually managed to load the module by creating a new Docker image based on your default `bitnami-docker-redis-cluster` image. But the issues appeared when trying to load the module into Redis. I had to copy your run.sh script locally and modify the ARGS variable to include my `--loadmodule module.so`. This works ok for now, but I will have to keep an eye on your run.sh for future changes, a nice solution would be to allow people to inject additional Redis parameters via environment variables.

**Comment by dani8art** [comment]
Hi @marghidanu as far as I understand it should be a matter of supporting something like

```bash
$ docker run -d --name redis00 bitnami/redis-cluster --loadmodule module.so
```

And propagate it to the chart `values.yaml`, shouldn't be?

**Comment by marghidanu** [comment]
Hello, wouldn't that conpletly replace the default run.sh command which has some additional logic in there?

**Comment by dani8art** [comment]
Yes you are right it was a mistake, please try

```
docker run -d --name redis00 bitnami/redis-cluster /opt/bitnami/scripts/redis-cluster/run.sh --loadmodule module.so
```

**Comment by marghidanu** [comment]
Where in run.sh are the additional script arguments picked up and added to the script? 

```
if ! is_boolean_yes "$REDIS_CLUSTER_CREATOR"; then
    ARGS=("--port" "$REDIS_PORT_NUMBER")
    ARGS+=("--include" "${REDIS_BASE_DIR}/etc/redis.conf")

    if ! is_boolean_yes "$ALLOW_EMPTY_PASSWORD"; then
        ARGS+=("--requirepass" "$REDIS_PASSWORD")
        ARGS+=("--masterauth" "$REDIS_PASSWORD")
    else
        ARGS+=("--protected-mode" "no")
    fi

    if am_i_root; then
        exec gosu "$REDIS_DAEMON_USER" redis-server "${ARGS[@]}"
    else
        exec redis-server "${ARGS[@]}"
    fi
else
    redis_cluster_create "${nodes[@]}"
fi
```

**Comment by dani8art** [comment]
Hi @marghidanu you are right, in some other containers we have something like 

```
flags+=("$@")
```

I think it would work here as well, please see more in this PR #9
